apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: frontend
  name: frontend
spec:
  selector:
    matchLabels:
      service: frontend
  replicas: 1
  template:
    metadata:
      labels:
        service: frontend
        api: external
    spec:
      containers:
        - image: docker.io/nghiepnx/udagram-frontend:v7
          name: frontend
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: frontend
  name: frontend
spec:
  ports:
    - name: "8100"
      port: 8100
      targetPort: 80
  selector:
    service: frontend
#  type: LoadBalancer
